### ISSUE TITLE
33% Completion Submission

### ISSUE THREAD

**Issue by johnhenning** [wildmustard/Gaia-iOS#4]
Neural Network is trained, Home View with camera setup on application side. Server setup in progress for Parse and Neural Net. Ready for review! /cc @codepathreview

**Comment by minhkhang1795** [comment]
Please add a gif file for your submission! Also, in the future, it would be better if you guys [create issues to split up the work across the team members](https://guides.github.com/features/issues/)

Please call me again in this issue once you update your gif file :smile:

**Comment by Blistin** [comment]
![gaia-submission-1](https://cloud.githubusercontent.com/assets/6467543/13731804/127d51be-e949-11e5-9029-146e871b5b9b.gif)

**Comment by Blistin** [comment]
Added a .gif of what we have created so far, the image collection is just using a stock image. We had to use quicktime to record the video and then gif-ify it since the simulator cannot use the running camera view! Ready for review! /cc @codepathreview

**Comment by johnhenning** [comment]
@vuminhkhang1995

**Comment by minhkhang1795** [comment]
:+1: Great job on the first implementation sprint! The app is really starting to come together. There are 2 weeks left to complete all of the required stories so that you have an MVP (minimum viable product). The purpose of this is to get the minimum set of functionality implemented first and then focus on adding in optionals afterwards. This ensures you have all the basics in place before adding in the additionals and polish.

p/s: great application icon and launch screen though! :smile:
